version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  rocketmq-namesrv:
    image: apache/rocketmq:latest
    container_name: rocketmq-namesrv
    ports:
      - "9876:9876"
    command: sh mqnamesrv

  rocketmq-broker:
    image: apache/rocketmq:latest
    container_name: rocketmq-broker
    ports:
      - "10909:10909"
      - "10911:10911"
    depends_on:
      - rocketmq-namesrv
    environment:
      NAMESRV_ADDR: "rocketmq-namesrv:9876"
    command: sh mqbroker -n rocketmq-namesrv:9876 -c /data/brokerconf/broker.conf
    volumes:
      - "./data/brokerconf:/data/brokerconf"
      - rocketmq-broker-data:/data

  rocketmq-console:
    image: styletang/rocketmq-console-ng:latest
    container_name: rocketmq-console
    ports:
      - "8080:8080"
    depends_on:
      - rocketmq-namesrv
      - rocketmq-broker
    environment:
      JAVA_OPTS: "-Drocketmq.namesrv.addr=rocketmq-namesrv:9876 -Dcom.rocketmq.sendMessageWithVIPChannel=false"

volumes:
  redis-data:
  rocketmq-broker-data: