version: '3.8'

services:
  redis:
    image: redis:6.2.6
    container_name: redis
    ports:
      - "6379:6379"

  rocketmq-nameserver:
    image: apache/rocketmq:4.9.3
    container_name: rocketmq-nameserver
    ports:
      - "9876:9876"
    command: sh mqnamesrv

  rocketmq-broker:
    image: apache/rocketmq:4.9.3
    container_name: rocketmq-broker
    ports:
      - "10909:10909"
      - "10911:10911"
    environment:
      - "NAMESRV_ADDR=rocketmq-nameserver:9876"
      - "JAVA_OPT_EXT=-Duser.home=/opt -Drocketmq.broker.storePathRootDir=/opt/store -Drocketmq.broker.storePathCommitLog=/opt/store/commitlog"
    command:
          sh -c "chown 3000:3000 -R rocketmq-nameserver"
          sh -c "chown 3000:3000 -R rocketmq-broker"
          sh mqbroker -c /data/brokerconf/broker.conf
    volumes:
      - "./data/brokerconf:/data/brokerconf"
    depends_on:
      - rocketmq-nameserver

volumes:
  redis:
  rocketmq-data:

