spring:
  docker:
    compose:
      enabled: true
      files: docker-compose.yml

rocketmq:
  name-server: localhost:9876
  producer:
    group: lotteryGroup
    send-msg-timeout: 10000
  consumer:
    group: lotteryConsumerGroup
  topic: LotteryAttemptTopic

logging:
  level:
    root: INFO
    org.apache.rocketmq: DEBUG